# https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

development:
  hosts:
    localhost:
      ansible_connection: local
